version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "controller"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-q6nb1vxl3ooo"
s3_prefix = "controller"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
