AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  integrator

  integrator
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  IntegratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: integrator/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64 
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-west-2:566321601732:controller-notification

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IntegratorFunction:
    Description: "Integrator Lambda Function ARN"
    Value: !GetAtt IntegratorFunction.Arn
  IntegratorFunctionIamRole:
    Description: "Implicit IAM Role created for Integrator function"
    Value: !GetAtt IntegratorFunctionRole.Arn
